FROM registry.cn-beijing.aliyuncs.com/daxia/qingting:xflow_202210311809

COPY ./code /root/code
WORKDIR /root/code/

CMD ["php","/root/code/index.php"]


#docker build -t daxia/qingting:xflow_latest .