FROM registry.cn-beijing.aliyuncs.com/daxia/qingting:sqlmap_202211011440

COPY ./code /root/code

WORKDIR /root/code

CMD ["php","/root/code/index.php"]


#docker build -t daxia/qingting:sqlmap_latest .