version: "3.2"
services:
  mysqlserver:
    restart: always
    ports:
      - "33306:3306"
    image: daxia/qingting:mysql57
    environment:
      - MYSQL_DATABASE=edge
      - MYSQL_ROOT_PASSWORD=123
      - TZ=Asia/Shanghai
  control:
    restart: always
    container_name: main
    image: daxia/qingting:control_latest
    environment:
      - serverAddr=http://qingting.starcross.cn
      - token=4b2d6574e1ad0d5e8647f23295137b66
      - sceId=163
      - nodeId=612
      - taskId=163
      - concurrent=4
    links:
      - mysqlserver:mysql_addr
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: "/Users/tangqingsong/mycode/QingTing/edge/control/code"
        target: "/root/code"
#  gitee:
#    image: daxia/qingting:gitee_latest
#    restart: always
#    links:
#      - mysqlserver:mysql_addr
#    volumes:
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/gitee/code"
#        target: "/root/code"
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/gitee/tools"
#        target: "/data/tools"
#    stdin_open: true
#    environment:
#      - serverAddr=http://txy8g.songboy.site:10000
#      - token=4b2d6574e1ad0d5e8647f23295137b66
#      - nodeId=126
#      - taskId=177
#      - concurrent=4
#    tty: true
#    command: /bin/sh -c "cd  /root/code/  && python3 main.py"
#  hema:
#    image: daxia/qingting:hema_latest
#    restart: always
#    links:
#      - mysqlserver:mysql_addr
#    volumes:
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/hema/code"
#        target: "/root/code"
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/hema/tools"
#        target: "/data/tools"
#    stdin_open: true
#    tty: true
#    command: /bin/sh -c "cd  /root/code/  && php index.php"
#  composer:
#    image: daxia/qingting:composer_latest
#    restart: always
#    links:
#      - mysqlserver:mysql_addr
#    volumes:
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/composer/code"
#        target: "/root/code"
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/composer/tools"
#        target: "/data/tools"
#      - type: bind
#        source: "/Users/tangqingsong/mycode/check"
#        target: "/data/code"
#    stdin_open: true
#    tty: true
#    command: /bin/sh -c "cd  /root/code/  && php index.php"
#  semgrep:
#    image: daxia/qingting:semgrep_latest
#    restart: always
#    links:
#      - mysqlserver:mysql_addr
#    volumes:
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/semgrep/code"
#        target: "/root/code"
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/semgrep/tools"
#        target: "/data/tools"
#      - type: bind
#        source: "/Users/tangqingsong/mycode/"
#        target: "/data/code"
#    stdin_open: true
#    tty: true
#    command: /bin/sh -c "cd  /root/code/  && php index.php"
#  rad:
#    image: daxia/qingting:rad_latest
#    restart: always
#    links:
#      - mysqlserver:mysql_addr
#    volumes:
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/rad/code"
#        target: "/root/code"
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/rad/tools"
#        target: "/data/tools"
#    stdin_open: true
#    tty: true
#    command: /bin/sh -c "cd  /root/code/  && php index.php"
#  xray:
#    image: daxia/qingting:xray_latest
#    restart: always
#    links:
#      - mysqlserver:mysql_addr
#    volumes:
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/xray/code"
#        target: "/root/code"
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/xray/tools"
#        target: "/data/tools"
#    stdin_open: true
#    tty: true
#    command: /bin/sh -c "cd  /root/code/  && php index.php"
#  sqlmap:
#    image: daxia/qingting:sqlmap_latest
#    restart: always
#    links:
#      - mysqlserver:mysql_addr
#    volumes:
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/sqlmap/code"
#        target: "/root/code"
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/sqlmap/tools"
#        target: "/data/tools"
#    stdin_open: true
#    tty: true
#    command: /bin/sh -c "cd  /root/code/  && php index.php"
#  dirmap:
#    image: daxia/qingting:dirmap_latest
#    restart: always
#    links:
#      - mysqlserver:mysql_addr
#    volumes:
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/dirmap/code"
#        target: "/root/code"
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/dirmap/tools"
#        target: "/data/tools"
#    stdin_open: true
#    tty: true
#    command: /bin/sh -c "cd  /root/code/  && php index.php"
#  dismap:
#    image: daxia/qingting:dismap_latest
#    restart: always
#    links:
#      - mysqlserver:mysql_addr
#    volumes:
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/dismap/code"
#        target: "/root/code"
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/dismap/tools"
#        target: "/data/tools"
#    stdin_open: true
#    tty: true
#    command: /bin/sh -c "cd  /root/code/  && php index.php"
#  oneforall:
#    image: daxia/qingting:oneforall_latest
#    restart: always
#    links:
#      - mysqlserver:mysql_addr
#    volumes:
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/oneforall/code"
#        target: "/root/code"
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/oneforall/tools/config"
#        target: "/OneForAll/config"
#    stdin_open: true
#    tty: true
#    command: /bin/sh -c "cd  /root/code/  && php index.php"
#  vulmap:
#    image: daxia/qingting:vulmap_latest
#    restart: always
#    links:
#      - mysqlserver:mysql_addr
#    volumes:
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/vulmap/code"
#        target: "/root/code"
#      - type: bind
#        source: "/Users/tangqingsong/mycode/QingTing/edge/vulmap/tools"
#        target: "/data/tools"
#    stdin_open: true
#    tty: true
#    command: /bin/sh -c "cd  /root/code/  && php index.php"
  knock:
    image: registry.cn-beijing.aliyuncs.com/daxia/qingting:knock_latest
    restart: always
    links:
      - mysqlserver:mysql_addr
    stdin_open: true
    tty: true
    command: /bin/sh -c "cd  /root/code/  && php index.php"
    volumes:
      - type: bind
        source: "/Users/tangqingsong/mycode/QingTing/edge/knock/code"
        target: "/root/code"
      - type: bind
        source: "/Users/tangqingsong/mycode/QingTing/edge/knock/tools"
        target: "/data/tools"
  nmap:
    image: registry.cn-beijing.aliyuncs.com/daxia/qingting:nmap_latest
    restart: always
    links:
      - mysqlserver:mysql_addr
    stdin_open: true
    tty: true
    command: /bin/sh -c "cd  /root/code/  && php index.php"
    volumes:
      - type: bind
        source: "/Users/tangqingsong/mycode/QingTing/edge/nmap/code"
        target: "/root/code"
      - type: bind
        source: "/Users/tangqingsong/mycode/QingTing/edge/nmap/tools"
        target: "/data/tools"
  masscan:
    image: registry.cn-beijing.aliyuncs.com/daxia/qingting:masscan_latest
    restart: always
    links:
      - mysqlserver:mysql_addr
    stdin_open: true
    tty: true
    command: /bin/sh -c "cd  /root/code/  && php index.php"
    volumes:
      - type: bind
        source: "/Users/tangqingsong/mycode/QingTing/edge/masscan/code"
        target: "/root/code"
      - type: bind
        source: "/Users/tangqingsong/mycode/QingTing/edge/masscan/tools"
        target: "/data/tools"